############################################ P O S T S #############################################

### post
POST http://localhost:8080/api/posts
Content-Type: application/json

{
        "userId":"657093331a6c4e5eb36955ac",
        "imageURL":"https://13630656.rocketcdn.me/wp-content/uploads/2020/01/Golden4.jpg.webp",
        "desc" : "blog post of nicky"
}

### update post
PUT http://localhost:8080/api/posts/6570938f1a6c4e5eb36955af
Content-Type: application/json

{
        "userId":"657093331a6c4e5eb36955ac",
        "imageURL":"https://13630656.rocketcdn.me/wp-content/uploads/2020/01/Golden4.jpg.webp",
        "desc" : "now posting"
}

### delete post
DELETE  http://localhost:8080/api/posts/6570938f1a6c4e5eb36955af
Content-Type: application/json

{
        "userId":"657093331a6c4e5eb36955ac"
}

############################################ U S E R #############################################

### REGISTER
POST http://localhost:8080/api/auth/register 
Content-Type: application/json

{
        "username":"admin",
        "password" : "admin"
}

### Login
POST http://localhost:8080/api/auth/login 
Content-Type: application/json

{
        "username":"21CS1244",
        "password" : "12345678"
}


### REGISTER
POST http://localhost:8080/api/auth/register 
Content-Type: application/json

{
  "name": "John Doe",
  "dp": "https://example.com/profile.jpg",
  "dept": "Engineering",
  "description": "A passionate engineer",
  "link": "https://example.com",
  "experience": {
    "role": "Software Engineer",
    "company": "TechCorp",
    "desc": "Worked on exciting projects"
  },
  "graduation_year": "2022",
  "friends": [],
  "recommendations": [],
  "skills": ["JavaScript", "React", "Node.js"],
  "username": "john_doe",
  "password": "securePassword"
}
